- hosts: all
  tasks:
  - name: Install the latest Apache Version
    yum: 
      name: httpd
      state: latest
    notify:
    - startservice
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted
