--- 
- hosts: all
  remote_user: root
  connection: ssh
  gather_facts: yes
  vars:
    username: vrasvc
  tasks:
  - name: Install the latest Apache Version
    yum: 
      name: httpd
      state: latest
    notify:
    - startservice
  - name: Sleep for 1500 Seconds
    wait_for: 
      timeout: 1500
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted
