- name: Install Snow Integration Manager
  ansible.builtin.unarchive:
  src: https://ftp.snowsoftware.com/SetupPackages/CurrentProductVersions/SIM/SetupSIM_5.40.zip
  dest: C:\Local Folder
  remote_src: yes
  ansible.windows.win_package:
  path: C:\Local Folder\SetupSIM_5.40\SetupSIM_5.40,exe
  state: present
  log_path: D:\logs\snow-{{lookup('pipe', 'date +%Y%m%dT%H%M%S')}}.log
