--- 
- 
  ansible.builtin.unarchive: ~
  ansible.windows.win_package: ~
  dest: "C:\\Local Folder"
  log_path: "D:\\logs\\snow-{{lookup('pipe', 'date +%Y%m%dT%H%M%S')}}.log"
  name: "Install Snow Integration Manager"
  path: "C:\\Local Folder\\SetupSIM_5.40\\SetupSIM_5.40,exe"
  remote_src: true
  src: "https://ftp.snowsoftware.com/SetupPackages/CurrentProductVersions/SIM/SetupSIM_5.40.zip"
  state: present
